### ISSUE TITLE
Browser demo hangs when trying to complete tokens starting with double-quote

### ISSUE THREAD

**Issue by smaximov** [imagineui/imagineui#4]
# Steps to reproduce

1. Go to the [Sandbox](https://imagineui.netlify.com/).
2. Place the cursor on the line

    ``` text
    Blocks "Description", "Subscription" aligned in two columns
    ```

    after `"Subscription"`.

3. Enter a comma, open a double-quote, start typing "Partners":

   ![image](https://user-images.githubusercontent.com/1370047/72887610-1bebb700-3d1d-11ea-97a4-2dd2053702f7.png)

# Expected behavior

You can either finish typing "Partners" or select it from the completion suggestions popup.

# Actual behavior

The page starts responding slower the more characters (after the opening double-quote) you type, until it hangs. It also hangs if you select a suggestion.

# Environment

The issue can be reproduced in the following browsers:

* Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0.
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by v4dkou** [comment]
@smaximov Thanks a lot!

I've encountered this issue 2-3 times during the development but couldn't reproduce it reliably.

Going to investigate it this weekend.

**Comment by smaximov** [comment]
It also hangs in Chrome (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36), but for a shorter period of time.

I cannot reproduce the issue in Safari (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15)

**Comment by v4dkou** [comment]
@smaximov Fixed the RegEx for parsing string literals; I went a little overboard with my first attempt.
https://github.com/imagineui/imagineui/commit/09e2b1df711b72a80e34058c6582a2e6c9c3edbf

While at it, I've added quote escapes in literals, so you can do something like
`Header "Cafe \"UX Heaven\""`

Going to ship it in the next release.
You can test the latest version in the canary build here:
https://imagineui.netlify.com/
