### ISSUE TITLE
The github page (imagineui.github.io) seems to be captured / full of spam or something more

### ISSUE THREAD

**Issue by funkvn** [imagineui/imagineui#42]
Try it by youself: https://imagineui.github.io -- but be warned!

It may concern the other repositories (https://github.com/imagineui/imagineui.github.io, https://github.com/imagineui/imagineui-website), did not check this yet.

**Comment by v4dkou** [comment]
Fixed, thanks for the message!

The repo itself was fine; imagineui.github.io was redirecting to imagineui.io, a domain name I don't own anymore due to Namecheap booting off Russian customers + other available registrars not being able to take over .io domain names
